<?php

/**
 * @file
 * Contains capetrials_custom_migration.module.
 */

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;

define('CUSTOM_MIGRATION_PREFIX', 'capetrials_');

/**
 * Implementation of hook_migrate_prepare_row().
 */
function capetrials_custom_migration_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  // Most of the code is broken out into separate files to make it easier to see
  // what is needed for each individual change.

  // Comment out anything not needed, or add more.

  \Drupal::moduleHandler()->loadInclude('capetrials_custom_migration', 'inc', '/includes/d6_colorbox');
  capetrials_custom_migration_colorbox($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_filter');
  // custom_migration_filter($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_block');
  // custom_migration_block($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_node_reference');
  // custom_migration_node_reference($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_address');
  // custom_migration_address($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_link');
  // custom_migration_link($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_geofield');
  // custom_migration_geofield($row, $source, $migration);

  // \Drupal::moduleHandler()->loadInclude('custom_migration', 'inc', '/includes/d7_geolocation');
  // custom_migration_geolocation($row, $source, $migration);

}
